export const GET_SUMMARY   = 'meteo.GET_SUMMARY'
export const GET_FORECAST  = 'meteo.GET_FORECAST'
export const GET_STATISTIC = 'meteo.GET_STATISTIC'
export const GET_KINDEX    = 'meteo.GET_KINDEX'
export const GET_HEATMAP   = 'meteo.GET_HEATMAP'